version: 0.2
env:
  variables:
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot --output-path ${BUILD_FOLDER} --base-href /
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: '${BUILD_FOLDER}*'
  discard-paths: yes